apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast-service 
spec:
  selector:
    app: {{ .Release.Name }}-cast-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8000
  type: ClusterIP