apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-movie-db-statefulset
spec:
  serviceName: {{ .Release.Name }}-movie-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine
        env:
        - name: POSTGRES_USER
          value: {{ .Values.movie_service.database.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.movie_service.database.password }}
        - name: POSTGRES_DB
          value: {{ .Values.movie_service.database.db }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres_data_movie
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres_data_movie
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  selector:
    app: {{ .Release.Name }}-movie-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

