apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie-service
spec:
  selector:
    app: {{ .Release.Name }}-movie-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: ClusterIP