apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-service-deployment
spec:
  replicas: {{ .Values.movie_service.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie-service
    spec:
      containers:
      - name: {{ .Release.Name }}-movie-service
        image: '{{ .Values.movie_service.repository }}:{{ .Values.movie_service.tag | default .Chart.AppVersion }}'
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: {{ .Values.movie_service.database.uri }}
        - name: CAST_SERVICE_HOST_URL
          value: {{ .Values.cast_service.host_url }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie-service
spec:
  selector:
    app: {{ .Release.Name }}-movie-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: ClusterIP

