apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  selector:
    app: {{ .Release.Name }}-movie-db
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432